#!/bin/bash

# Auto-Installation Script
# ========================
# This script aims to automate the process of installing Arch Linux onto my Lenovo T440s.
# As a result, the configuration is opinionated. However, the script generally follows
# along with the guide on the [Arch Linux wiki](https://wiki.archlinux.org/index.php/Installation_guide).
#
# Pre-Installation Setup
# ----------------------
# It's assumed that this script will be run after cloning the git repo. As a result,
# there's a number of steps that will need to be taken manually in preparation.
#
### Configure WiFi Connection
# 1. `systemctl stop dhcpcd@<TAB>`
# 2. `ip link set wlp3s0 up`
# 3. `wpa_supplicant -B -i wlp3s0 -c <(wpa_passphrase "<SSID>" "<PASSPHRASE>")`
# 4. `systemctl start dhcpcd@wlp3s0.service`
# 5. `ping 8.8.8.8`
#
### Clone Git Repo
# 1. `mount -o remount,size=2G /run/archiso/cowspace`
# 2. `pacman -Sy git`
# 3. `git clone --depth 1 https://github.com/ScottHamper/t440s-arch-install.git`
#
# Alternatively, without Git:
# 1. `curl https://raw.githubusercontent.com/ScottHamper/t440s-arch-install/master/install -o install`

# Determine root/boot disks by using `lsblk`
while getopts ":r:b:h:" arg; do
    case ${arg} in
        r) root_disk=$OPTARG;;
        b) boot_disk=$OPTARG;;
        h) hostname=$OPTARG;;
    esac
done

#TODO: Validation of args

timedatectl set-ntp true

# Wipe out the GPT and create brand new partitions
sgdisk --clear ${root_disk}
sgdisk -n 1:0:0 ${root_disk}

sgdisk --clear ${boot_disk}
sgdisk -n 1:0:+200M ${boot_disk}
sgdisk -n 2:0:+512M -t 2:ef00 ${boot_disk}

# LUKS/Formatting
head -c 4096 < /dev/random > /root/crypto_keyfile.bin
chmod 0400 /root/crypto_keyfile.bin
cryptsetup -q --use-random --key-size 512 --iter-time 2000 luksFormat ${root_disk} /root/crypto_keyfile.bin
cryptsetup open ${root_disk} cryptroot --key-file /root/crypto_keyfile.bin
mkfs.btrfs -f /dev/mapper/cryptroot
mkfs.btrfs -f ${boot_disk}1
mkfs.vfat -F32 ${boot_disk}2

# Labeling
btrfs filesystem label /dev/mapper/cryptroot T440S_ROOT
btrfs filesystem label ${boot_disk}1 T440S_BOOT
fatlabel ${boot_disk}2 T440S_ESP

# Mounting
mount /dev/mapper/cryptroot /mnt
mkdir /mnt/boot
mount ${boot_disk}1 /mnt/boot
mkdir /mnt/boot/efi
mount ${boot_disk}2 /mnt/boot/efi

# Installation
pacstrap /mnt base btrfs-progs iw wpa_supplicant refind-efi git
genfstab -U /mnt >> /mnt/etc/fstab

# Chroot Prep
mv /root/crypto_keyfile.bin /mnt
chmod 000 /mnt/crypto_keyfile.bin
chmod 600 /mnt/boot/initramfs-linux*
ln -sf /usr/share/zoneinfo/America/New_York /mnt/etc/localtime
echo "en_US.UTF-8 UTF-8" > /mnt/etc/locale.gen
echo "LANG=en_US.UTF-8" > /mnt/etc/locale.conf
echo "KEYMAP=dvorak" > /mnt/etc/vconsole.conf
echo ${hostname} > /mnt/etc/hostname
sed -i -e 's/^FILES=""$/FILES="\/crypto_keyfile.bin"/g' /mnt/etc/mkinitcpio.conf
sed -i -e 's/^HOOKS=".*"$/HOOKS="base udev autodetect modconf keyboard keymap block encrypt filesystems fsck"/g' /mnt/etc/mkinitcpio.conf

# Chroot
arch-chroot /mnt << EOF
hwclock --systohc # Assumes hardware clock is UTC
locale-gen
mkinitcpio -p linux

refind-install
rm /boot/refind_linux.conf
mkdir /boot/efi/EFI/refind/themes
git clone -b t440s --depth 1 https://github.com/ScottHamper/rEFInd-minimal.git /boot/efi/EFI/refind/themes/rEFInd-minimal
rm -rf /boot/efi/EFI/refind/themes/rEFInd-minimal/.git
EOF

#rEFInd
cat << EOF > /mnt/boot/efi/EFI/refind/refind.conf
include themes/rEFInd-minimal/theme.conf
dont_scan_volumes "T440S_ROOT,T440S_BOOT,T440S_ESP"
timeout 5
use_graphics_for + linux

menuentry "Arch Linux" {
    icon /EFI/refind/themes/rEFInd-minimal/icons/os_arch.png
    volume "$(blkid -s PARTUUID -o value ${boot_disk}1)"
    loader /vmlinuz-linux
    initrd /initramfs-linux.img
    options "cryptdevice=UUID=$(blkid -s UUID -o value ${root_disk}1):cryptroot root=/dev/mapper/cryptroot rw quiet"
}
EOF
